#!/usr/bin/env bash

set -u

usage() {
  cat <<'EOF'
Usage:
  ./scripts/patch-report.sh <user@host> <report-path> [--http-url <url>]...

Examples:
  ./scripts/patch-report.sh debian@10.0.0.10 \
    docs/reports/2026-05-03-ops-dev-patching.md

  ./scripts/patch-report.sh debian@10.0.0.10 \
    docs/reports/2026-05-03-ops-dev-patching.md \
    --http-url http://10.0.0.10/healthz \
    --http-url http://10.0.0.10/api/healthz
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

if [ "$#" -lt 2 ]; then
  usage
  exit 1
fi

target="$1"
report_path="$2"
shift 2

http_urls=()

while [ "$#" -gt 0 ]; do
  case "$1" in
    --http-url)
      if [ "${2:-}" = "" ]; then
        printf 'Missing value for --http-url\n' >&2
        exit 1
      fi
      http_urls+=("$2")
      shift 2
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage
      exit 1
      ;;
  esac
done

ssh_opts=(
  -o BatchMode=yes
  -o ConnectTimeout=5
  -o StrictHostKeyChecking=accept-new
)

run_remote() {
  ssh "${ssh_opts[@]}" "$target" "$1"
}

capture_remote() {
  command="$1"
  output_file="$(mktemp)"

  if run_remote "$command" >"$output_file" 2>&1; then
    cat "$output_file"
    rm -f "$output_file"
    return 0
  fi

  cat "$output_file"
  rm -f "$output_file"
  return 1
}

capture_local() {
  command="$1"
  output_file="$(mktemp)"

  if sh -c "$command" >"$output_file" 2>&1; then
    cat "$output_file"
    rm -f "$output_file"
    return 0
  fi

  cat "$output_file"
  rm -f "$output_file"
  return 1
}

report_dir="$(dirname "$report_path")"
mkdir -p "$report_dir"
report_abs="$(cd "$report_dir" && pwd)/$(basename "$report_path")"

hostname_output="$(capture_remote 'hostnamectl --static' || true)"
hostname_value="$(printf '%s\n' "$hostname_output" | sed -n '1p')"
if [ "$hostname_value" = "" ]; then
  hostname_value="$target"
fi

validation_cmd=(./scripts/validate-host.sh "$target")
for http_url in "${http_urls[@]}"; do
  validation_cmd+=(--http-url "$http_url")
done

validation_output_file="$(mktemp)"
if "${validation_cmd[@]}" >"$validation_output_file" 2>&1; then
  validation_status=0
  validation_result="PASS"
else
  validation_status=$?
  validation_result="FAIL"
fi

{
  printf '# %s Patching Report\n\n' "$hostname_value"
  printf -- '- Date: `%s`\n' "$(date +%F)"
  printf -- '- Host: `%s`\n' "$hostname_value"
  printf -- '- SSH target: `%s`\n' "$target"
  printf -- '- Generated by: `scripts/patch-report.sh`\n'
  printf -- '- Result: `%s`\n\n' "$validation_result"

  printf '## Package State\n\n'
  printf '### Upgradable packages\n\n'
  printf 'Command:\n\n```sh\nssh %s '\''apt list --upgradable'\''\n```\n\n' "$target"
  printf 'Output:\n\n```text\n'
  capture_remote "apt list --upgradable" || true
  printf '```\n\n'

  printf '### Held packages\n\n'
  printf 'Command:\n\n```sh\nssh %s '\''apt-mark showhold'\''\n```\n\n' "$target"
  printf 'Output:\n\n```text\n'
  capture_remote "apt-mark showhold" || true
  printf '```\n\n'

  printf '## Host Health\n\n'
  printf '### System state\n\n'
  printf 'Command:\n\n```sh\nssh %s '\''systemctl is-system-running'\''\n```\n\n' "$target"
  printf 'Output:\n\n```text\n'
  capture_remote "systemctl is-system-running" || true
  printf '```\n\n'

  printf '### Failed units\n\n'
  printf 'Command:\n\n```sh\nssh %s '\''systemctl --failed --no-pager'\''\n```\n\n' "$target"
  printf 'Output:\n\n```text\n'
  capture_remote "systemctl --failed --no-pager" || true
  printf '```\n\n'

  printf '### Firewall status\n\n'
  printf 'Command:\n\n```sh\nssh %s '\''sudo ufw status verbose'\''\n```\n\n' "$target"
  printf 'Output:\n\n```text\n'
  capture_remote "sudo ufw status verbose" || true
  printf '```\n\n'

  printf '### fail2ban status\n\n'
  printf 'Command:\n\n```sh\nssh %s '\''sudo fail2ban-client status sshd'\''\n```\n\n' "$target"
  printf 'Output:\n\n```text\n'
  capture_remote "sudo fail2ban-client status sshd" || true
  printf '```\n\n'

  printf '### Reboot requirement\n\n'
  printf 'Command:\n\n```sh\nssh %s '\''if [ -f /var/run/reboot-required ]; then cat /var/run/reboot-required; else echo no-reboot-required; fi'\''\n```\n\n' "$target"
  printf 'Output:\n\n```text\n'
  capture_remote "if [ -f /var/run/reboot-required ]; then cat /var/run/reboot-required; else echo no-reboot-required; fi" || true
  printf '```\n\n'

  if [ "${#http_urls[@]}" -gt 0 ]; then
    printf '## HTTP Checks\n\n'
    for http_url in "${http_urls[@]}"; do
      printf '### `%s`\n\n' "$http_url"
      printf 'Command:\n\n```sh\ncurl -sS -i --max-time 5 %s\n```\n\n' "$http_url"
      printf 'Output:\n\n```text\n'
      capture_local "curl -sS -i --max-time 5 '$http_url'" || true
      printf '\n```\n\n'
    done
  fi

  printf '## Validator Run\n\n'
  printf 'Command:\n\n```sh\n'
  printf '%s' "${validation_cmd[0]}"
  for arg in "${validation_cmd[@]:1}"; do
    printf ' %q' "$arg"
  done
  printf '\n```\n\n'
  printf 'Output:\n\n```text\n'
  cat "$validation_output_file"
  printf '```\n'
} >"$report_abs"

rm -f "$validation_output_file"
printf 'Wrote report: %s\n' "$report_abs"

if [ "$validation_status" -ne 0 ]; then
  exit "$validation_status"
fi
